// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VenueBookingSystem.Data;

#nullable disable

namespace cloudpart2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VenueBookingSystem.Models.Booking", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingID"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("EventID")
                        .HasColumnType("int");

                    b.Property<string>("SpecialRequests")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Confirmed");

                    b.Property<int>("VenueID")
                        .HasColumnType("int");

                    b.HasKey("BookingID");

                    b.HasIndex("EventID");

                    b.HasIndex("VenueID", "BookingDate")
                        .IsUnique()
                        .HasDatabaseName("UQ_Booking_DateTime");

                    b.ToTable("Bookings", "dbo");
                });

            modelBuilder.Entity("VenueBookingSystem.Models.BookingViewModel", b =>
                {
                    b.Property<DateTime>("BookingCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BookingID")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationHours")
                        .HasColumnType("int");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventID")
                        .HasColumnType("int");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialRequests")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VenueID")
                        .HasColumnType("int");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("vw_EnhancedBookings", "dbo");
                });

            modelBuilder.Entity("VenueBookingSystem.Models.Event", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DurationHours")
                        .HasColumnType("int");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EventTypeID")
                        .HasColumnType("int");

                    b.Property<string>("OrganizerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EventID");

                    b.HasIndex("EventTypeID");

                    b.ToTable("Events", "dbo");
                });

            modelBuilder.Entity("VenueBookingSystem.Models.EventType", b =>
                {
                    b.Property<int>("EventTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventTypeID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("EventTypeID");

                    b.ToTable("EventTypes", "dbo");

                    b.HasData(
                        new
                        {
                            EventTypeID = 1,
                            CategoryName = "Conference",
                            CreatedAt = new DateTime(2026, 6, 12, 14, 22, 57, 94, DateTimeKind.Local).AddTicks(3821),
                            Description = "Business conferences and seminars",
                            DisplayOrder = 1,
                            IsActive = true
                        },
                        new
                        {
                            EventTypeID = 2,
                            CategoryName = "Wedding",
                            CreatedAt = new DateTime(2026, 6, 12, 14, 22, 57, 94, DateTimeKind.Local).AddTicks(3823),
                            Description = "Wedding ceremonies and receptions",
                            DisplayOrder = 2,
                            IsActive = true
                        },
                        new
                        {
                            EventTypeID = 3,
                            CategoryName = "Workshop",
                            CreatedAt = new DateTime(2026, 6, 12, 14, 22, 57, 94, DateTimeKind.Local).AddTicks(3825),
                            Description = "Training workshops and classes",
                            DisplayOrder = 3,
                            IsActive = true
                        },
                        new
                        {
                            EventTypeID = 4,
                            CategoryName = "Concert",
                            CreatedAt = new DateTime(2026, 6, 12, 14, 22, 57, 94, DateTimeKind.Local).AddTicks(3827),
                            Description = "Music concerts and performances",
                            DisplayOrder = 4,
                            IsActive = true
                        },
                        new
                        {
                            EventTypeID = 5,
                            CategoryName = "Corporate Event",
                            CreatedAt = new DateTime(2026, 6, 12, 14, 22, 57, 94, DateTimeKind.Local).AddTicks(3829),
                            Description = "Corporate meetings and events",
                            DisplayOrder = 5,
                            IsActive = true
                        },
                        new
                        {
                            EventTypeID = 6,
                            CategoryName = "Birthday Party",
                            CreatedAt = new DateTime(2026, 6, 12, 14, 22, 57, 94, DateTimeKind.Local).AddTicks(3830),
                            Description = "Birthday celebrations",
                            DisplayOrder = 6,
                            IsActive = true
                        },
                        new
                        {
                            EventTypeID = 7,
                            CategoryName = "Exhibition",
                            CreatedAt = new DateTime(2026, 6, 12, 14, 22, 57, 94, DateTimeKind.Local).AddTicks(3832),
                            Description = "Art and trade exhibitions",
                            DisplayOrder = 7,
                            IsActive = true
                        },
                        new
                        {
                            EventTypeID = 8,
                            CategoryName = "Other",
                            CreatedAt = new DateTime(2026, 6, 12, 14, 22, 57, 94, DateTimeKind.Local).AddTicks(3834),
                            Description = "Other types of events",
                            DisplayOrder = 8,
                            IsActive = true
                        });
                });

            modelBuilder.Entity("VenueBookingSystem.Models.Venue", b =>
                {
                    b.Property<int>("VenueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VenueID"));

                    b.Property<string>("AvailabilityStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Available");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastMaintenanceDate")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("NextAvailableDate")
                        .HasColumnType("datetime");

                    b.Property<string>("OperatingHours")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VenueID");

                    b.ToTable("Venues", "dbo");
                });

            modelBuilder.Entity("VenueBookingSystem.Models.Booking", b =>
                {
                    b.HasOne("VenueBookingSystem.Models.Event", "Event")
                        .WithMany("Bookings")
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VenueBookingSystem.Models.Venue", "Venue")
                        .WithMany("Bookings")
                        .HasForeignKey("VenueID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("VenueBookingSystem.Models.Event", b =>
                {
                    b.HasOne("VenueBookingSystem.Models.EventType", "EventType")
                        .WithMany()
                        .HasForeignKey("EventTypeID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EventType");
                });

            modelBuilder.Entity("VenueBookingSystem.Models.Event", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("VenueBookingSystem.Models.Venue", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
